services:
  db:
   image: redis
   container_name: redis
   command: redis-server --save 60 1 --loglevel warning
   ports:
     - "6379:6379"
   volumes:
     - './data:/data'
  web:
   build: .
   container_name: myflask
   ports:
     - "80:80"
   depends_on:
     - db
